### ISSUE TITLE
Why reinvent the wheel? OVH already has an OpenAPI spec... 🤨

### ISSUE THREAD

**Issue by jbwittner** [bmassemin/ovh-sdk-net#1]
So... what's the point of this SDK?

Did you just want to code for the sake of it? Because FYI, OVH already provides an [**OpenAPI spec**](https://eu.api.ovh.com/1.0/cloud.json?format=openapi3) that handles all this automatically.

Seriously, why are you wasting time (and everyone else’s) building something that could be generated in a few clicks?

Next time, maybe check if the tools you need already exist before putting in all this unnecessary work. 🙄

Kiss kiss ❤️

**Comment by bmassemin** [comment]
Thank you for your support! Feel free to contribute if you would like to improve the project!
