### ISSUE TITLE
Duplicate ? – OpenAPI Specs for OVH API Already Exist

### ISSUE THREAD

**Issue by CorentinGS** [bmassemin/ovh-sdk-net#2]
#### Description:

Hey there, brilliant developer! 👋

I just stumbled upon your package that claims to generate OpenAPI specs for the OVH API. That’s really cool and all... except **OVH has already provided the OpenAPI specs** publicly, in a beautiful, ready-to-use format.

Here's the link:  
[OVH API OpenAPI 3 Spec](https://eu.api.ovh.com/1.0/cloud.json?format=openapi3) 🎉

Now, I don’t want to roast you too hard, but let’s just say this package is a **stellar example of effort duplication**. While your hard work is appreciated, it seems like you’ve embarked on a solo mission to reinvent the wheel. 🚴‍♂️💨

#### Why This Might Be a Problem:
1. **Already exists**: OVH already provides a fully functional OpenAPI 3 spec, and anyone can fetch it directly.
2. **Maintenance burden**: Now you’ll have to maintain your generated specs to match OVH’s, which sounds like a job no one asked for.
3. **Efficiency**: A couple of hours of development time could have been saved just by googling "OVH OpenAPI spec". 😅

#### Suggestions:
- Maybe rename the package to “How I Wrote Code for No Reason”?
- Alternatively, update the README to inform people that the OpenAPI spec is already available so no one else falls into the same pit.
- Or just delete the repo? 🤷‍♂️

Kidding aside, I’m sure you had good intentions, but for future reference: when an API provider already gives OpenAPI specs, you can save yourself some headaches (and PRs like this one) by simply **using** them.

Best regards,  
A friendly code reviewer, trying to save you from unnecessary toil.

**Comment by bmassemin** [comment]
Thank you for your support! Feel free to contribute if you would like to improve the project!
